# This block is a workaround for https://forum.gitlab.com/t/docker-dind-stops-working-after-12-1-0-update/28664/4.
services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

stages: [download, test, build, deploy]

download-vectors:
  stage: download
  script:
    - wget https://github.com/explosion/sense2vec/releases/download/v1.0.0/s2v_reddit_2015_md.tar.gz
    - tar -xzf s2v_reddit_2015_md.tar.gz
    - rm s2v_reddit_2015_md.tar.gz
  artifacts:
    paths: [s2v_old]

test-server:
  stage: test
  image: docker/compose
  script: docker-compose -f docker-compose.yml -f docker-compose.test.yml
    up --build --abort-on-container-exit --exit-code-from app

test-spec:
  stage: test
  image: node
  script:
    - npm i -g @stoplight/spectral
    - spectral lint docs/openapi.yaml

build-image:
  stage: build
  image: docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - version=$(grep version docs/openapi.yaml -m 1)
    - 'version=${version#*: }'
    - version=$(echo $version | cut -d "'" -f 2)
    - echo v$version > version.txt
    - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$(cat version.txt) .
    - docker push $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE:$(cat version.txt)
  artifacts:
    paths: [version.txt]
  only: [master]

build-docs:
  stage: build
  image: node
  script:
    - npm i -g redoc-cli
    - redoc-cli bundle docs/openapi.yaml --title 'spaCy'
  artifacts:
    paths: [redoc-static.html]
  only: [master]

docker-hub:
  stage: deploy
  image: docker:dind
  script:
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin https://index.docker.io/v1/
    - docker pull $CI_REGISTRY_IMAGE
    - docker pull $CI_REGISTRY_IMAGE:$(cat version.txt)
    - docker tag $CI_REGISTRY_IMAGE $DOCKER_HUB_USER/spacy-server
    - docker tag $CI_REGISTRY_IMAGE:$(cat version.txt) $DOCKER_HUB_USER/spacy-server:$(cat version.txt)
    - docker push $DOCKER_HUB_USER/spacy-server
    - docker push $DOCKER_HUB_USER/spacy-server:$(cat version.txt)
  only: [master]

pages:
  stage: deploy
  script:
    - mkdir public
    - cp redoc-static.html public/index.html
  artifacts:
    paths: [public]
  only: [master]