# See https://forum.gitlab.com/t/docker-dind-stops-working-after-12-1-0-update/28664/4.

services:
  - name: docker:dind
    entrypoint: ['env', '-u', 'DOCKER_HOST']
    command: ['dockerd-entrypoint.sh']

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: '' # See https://github.com/docker-library/docker/pull/166.

stages: [download, test, build, deploy]

download-vectors:
  stage: download
  script:
    - wget -q https://github.com/explosion/sense2vec/releases/download/v1.0.0/s2v_reddit_2015_md.tar.gz
    - tar -xzf s2v_reddit_2015_md.tar.gz -C src
    - rm s2v_reddit_2015_md.tar.gz
  artifacts:
    paths: [s2v_old]

test-server:
  stage: test
  image: docker/compose
  script: SPACY_MODEL=en_core_web_sm docker-compose --project-directory .
    -f docker/docker-compose.yml -f docker/docker-compose.test.yml
    up --build --abort-on-container-exit --exit-code-from app

test-spec:
  stage: test
  image: node
  script: npx @stoplight/spectral lint docs/openapi.yaml

build-docs:
  stage: build
  image: node
  script: npx redoc-cli bundle docs/openapi.yaml --title 'spaCy Server'
  artifacts:
    paths: [redoc-static.html]
  only: [master]

docker-hub:
  stage: deploy
  image: docker:dind
  script: sh scripts/deploy.sh
  only: [master]

pages:
  stage: deploy
  script:
    - mkdir public
    - cp redoc-static.html public/index.html
  artifacts:
    paths: [public]
  only: [master]