version: '3.7'
services:
  app:
    image: python:3.7
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: cache
        target: /usr/local/lib/python3.7/site-packages
volumes:
  cache: