# A virtual environment caches dependencies instead of a Docker volume because the volume randomly gets corrupted.
version: '3.7'
services:
  app:
    image: python:3.8
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app